version: '3'

services:
  playground:
    build: .
    container_name: playground
    command: jupyter notebook --ip=0.0.0.0 --no-browser --allow-root
    volumes:
      - .:/app
    ports:
      - 8888:8888